package pe.gob.minjus.sisarb.auto.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.minjus.sisarb.auto.domain.Menu;
import pe.gob.minjus.sisarb.auto.domain.MenuExample;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    long countByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    int deleteByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    int insert(Menu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    int insertSelective(Menu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    List<Menu> selectByExample(MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    Menu selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    int updateByExampleSelective(@Param("row") Menu row, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    int updateByExample(@Param("row") Menu row, @Param("example") MenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    int updateByPrimaryKeySelective(Menu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    int updateByPrimaryKey(Menu row);
}