package pe.gob.minjus.sisarb.auto.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MenuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public MenuExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMenuIdIsNull() {
            addCriterion("MENU_ID is null");
            return (Criteria) this;
        }

        public Criteria andMenuIdIsNotNull() {
            addCriterion("MENU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMenuIdEqualTo(Long value) {
            addCriterion("MENU_ID =", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotEqualTo(Long value) {
            addCriterion("MENU_ID <>", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThan(Long value) {
            addCriterion("MENU_ID >", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("MENU_ID >=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThan(Long value) {
            addCriterion("MENU_ID <", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdLessThanOrEqualTo(Long value) {
            addCriterion("MENU_ID <=", value, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdIn(List<Long> values) {
            addCriterion("MENU_ID in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotIn(List<Long> values) {
            addCriterion("MENU_ID not in", values, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdBetween(Long value1, Long value2) {
            addCriterion("MENU_ID between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andMenuIdNotBetween(Long value1, Long value2) {
            addCriterion("MENU_ID not between", value1, value2, "menuId");
            return (Criteria) this;
        }

        public Criteria andNombreIsNull() {
            addCriterion("NOMBRE is null");
            return (Criteria) this;
        }

        public Criteria andNombreIsNotNull() {
            addCriterion("NOMBRE is not null");
            return (Criteria) this;
        }

        public Criteria andNombreEqualTo(String value) {
            addCriterion("NOMBRE =", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotEqualTo(String value) {
            addCriterion("NOMBRE <>", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThan(String value) {
            addCriterion("NOMBRE >", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThanOrEqualTo(String value) {
            addCriterion("NOMBRE >=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThan(String value) {
            addCriterion("NOMBRE <", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThanOrEqualTo(String value) {
            addCriterion("NOMBRE <=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLike(String value) {
            addCriterion("NOMBRE like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotLike(String value) {
            addCriterion("NOMBRE not like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreIn(List<String> values) {
            addCriterion("NOMBRE in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotIn(List<String> values) {
            addCriterion("NOMBRE not in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreBetween(String value1, String value2) {
            addCriterion("NOMBRE between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotBetween(String value1, String value2) {
            addCriterion("NOMBRE not between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andTipoIsNull() {
            addCriterion("TIPO is null");
            return (Criteria) this;
        }

        public Criteria andTipoIsNotNull() {
            addCriterion("TIPO is not null");
            return (Criteria) this;
        }

        public Criteria andTipoEqualTo(String value) {
            addCriterion("TIPO =", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotEqualTo(String value) {
            addCriterion("TIPO <>", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoGreaterThan(String value) {
            addCriterion("TIPO >", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoGreaterThanOrEqualTo(String value) {
            addCriterion("TIPO >=", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoLessThan(String value) {
            addCriterion("TIPO <", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoLessThanOrEqualTo(String value) {
            addCriterion("TIPO <=", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoLike(String value) {
            addCriterion("TIPO like", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotLike(String value) {
            addCriterion("TIPO not like", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoIn(List<String> values) {
            addCriterion("TIPO in", values, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotIn(List<String> values) {
            addCriterion("TIPO not in", values, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoBetween(String value1, String value2) {
            addCriterion("TIPO between", value1, value2, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotBetween(String value1, String value2) {
            addCriterion("TIPO not between", value1, value2, "tipo");
            return (Criteria) this;
        }

        public Criteria andMenuPadreIsNull() {
            addCriterion("MENU_PADRE is null");
            return (Criteria) this;
        }

        public Criteria andMenuPadreIsNotNull() {
            addCriterion("MENU_PADRE is not null");
            return (Criteria) this;
        }

        public Criteria andMenuPadreEqualTo(Long value) {
            addCriterion("MENU_PADRE =", value, "menuPadre");
            return (Criteria) this;
        }

        public Criteria andMenuPadreNotEqualTo(Long value) {
            addCriterion("MENU_PADRE <>", value, "menuPadre");
            return (Criteria) this;
        }

        public Criteria andMenuPadreGreaterThan(Long value) {
            addCriterion("MENU_PADRE >", value, "menuPadre");
            return (Criteria) this;
        }

        public Criteria andMenuPadreGreaterThanOrEqualTo(Long value) {
            addCriterion("MENU_PADRE >=", value, "menuPadre");
            return (Criteria) this;
        }

        public Criteria andMenuPadreLessThan(Long value) {
            addCriterion("MENU_PADRE <", value, "menuPadre");
            return (Criteria) this;
        }

        public Criteria andMenuPadreLessThanOrEqualTo(Long value) {
            addCriterion("MENU_PADRE <=", value, "menuPadre");
            return (Criteria) this;
        }

        public Criteria andMenuPadreIn(List<Long> values) {
            addCriterion("MENU_PADRE in", values, "menuPadre");
            return (Criteria) this;
        }

        public Criteria andMenuPadreNotIn(List<Long> values) {
            addCriterion("MENU_PADRE not in", values, "menuPadre");
            return (Criteria) this;
        }

        public Criteria andMenuPadreBetween(Long value1, Long value2) {
            addCriterion("MENU_PADRE between", value1, value2, "menuPadre");
            return (Criteria) this;
        }

        public Criteria andMenuPadreNotBetween(Long value1, Long value2) {
            addCriterion("MENU_PADRE not between", value1, value2, "menuPadre");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("URL is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("URL is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("URL =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("URL <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("URL >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("URL >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("URL <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("URL <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("URL like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("URL not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("URL in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("URL not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("URL between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("URL not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andCommandIsNull() {
            addCriterion("COMMAND is null");
            return (Criteria) this;
        }

        public Criteria andCommandIsNotNull() {
            addCriterion("COMMAND is not null");
            return (Criteria) this;
        }

        public Criteria andCommandEqualTo(String value) {
            addCriterion("COMMAND =", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandNotEqualTo(String value) {
            addCriterion("COMMAND <>", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandGreaterThan(String value) {
            addCriterion("COMMAND >", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandGreaterThanOrEqualTo(String value) {
            addCriterion("COMMAND >=", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandLessThan(String value) {
            addCriterion("COMMAND <", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandLessThanOrEqualTo(String value) {
            addCriterion("COMMAND <=", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandLike(String value) {
            addCriterion("COMMAND like", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandNotLike(String value) {
            addCriterion("COMMAND not like", value, "command");
            return (Criteria) this;
        }

        public Criteria andCommandIn(List<String> values) {
            addCriterion("COMMAND in", values, "command");
            return (Criteria) this;
        }

        public Criteria andCommandNotIn(List<String> values) {
            addCriterion("COMMAND not in", values, "command");
            return (Criteria) this;
        }

        public Criteria andCommandBetween(String value1, String value2) {
            addCriterion("COMMAND between", value1, value2, "command");
            return (Criteria) this;
        }

        public Criteria andCommandNotBetween(String value1, String value2) {
            addCriterion("COMMAND not between", value1, value2, "command");
            return (Criteria) this;
        }

        public Criteria andIconIsNull() {
            addCriterion("ICON is null");
            return (Criteria) this;
        }

        public Criteria andIconIsNotNull() {
            addCriterion("ICON is not null");
            return (Criteria) this;
        }

        public Criteria andIconEqualTo(String value) {
            addCriterion("ICON =", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotEqualTo(String value) {
            addCriterion("ICON <>", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThan(String value) {
            addCriterion("ICON >", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThanOrEqualTo(String value) {
            addCriterion("ICON >=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThan(String value) {
            addCriterion("ICON <", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThanOrEqualTo(String value) {
            addCriterion("ICON <=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLike(String value) {
            addCriterion("ICON like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotLike(String value) {
            addCriterion("ICON not like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconIn(List<String> values) {
            addCriterion("ICON in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotIn(List<String> values) {
            addCriterion("ICON not in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconBetween(String value1, String value2) {
            addCriterion("ICON between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotBetween(String value1, String value2) {
            addCriterion("ICON not between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andAjaxIsNull() {
            addCriterion("AJAX is null");
            return (Criteria) this;
        }

        public Criteria andAjaxIsNotNull() {
            addCriterion("AJAX is not null");
            return (Criteria) this;
        }

        public Criteria andAjaxEqualTo(Short value) {
            addCriterion("AJAX =", value, "ajax");
            return (Criteria) this;
        }

        public Criteria andAjaxNotEqualTo(Short value) {
            addCriterion("AJAX <>", value, "ajax");
            return (Criteria) this;
        }

        public Criteria andAjaxGreaterThan(Short value) {
            addCriterion("AJAX >", value, "ajax");
            return (Criteria) this;
        }

        public Criteria andAjaxGreaterThanOrEqualTo(Short value) {
            addCriterion("AJAX >=", value, "ajax");
            return (Criteria) this;
        }

        public Criteria andAjaxLessThan(Short value) {
            addCriterion("AJAX <", value, "ajax");
            return (Criteria) this;
        }

        public Criteria andAjaxLessThanOrEqualTo(Short value) {
            addCriterion("AJAX <=", value, "ajax");
            return (Criteria) this;
        }

        public Criteria andAjaxIn(List<Short> values) {
            addCriterion("AJAX in", values, "ajax");
            return (Criteria) this;
        }

        public Criteria andAjaxNotIn(List<Short> values) {
            addCriterion("AJAX not in", values, "ajax");
            return (Criteria) this;
        }

        public Criteria andAjaxBetween(Short value1, Short value2) {
            addCriterion("AJAX between", value1, value2, "ajax");
            return (Criteria) this;
        }

        public Criteria andAjaxNotBetween(Short value1, Short value2) {
            addCriterion("AJAX not between", value1, value2, "ajax");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNull() {
            addCriterion("UPDATED is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNotNull() {
            addCriterion("UPDATED is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedEqualTo(String value) {
            addCriterion("UPDATED =", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotEqualTo(String value) {
            addCriterion("UPDATED <>", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThan(String value) {
            addCriterion("UPDATED >", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATED >=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThan(String value) {
            addCriterion("UPDATED <", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThanOrEqualTo(String value) {
            addCriterion("UPDATED <=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLike(String value) {
            addCriterion("UPDATED like", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotLike(String value) {
            addCriterion("UPDATED not like", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedIn(List<String> values) {
            addCriterion("UPDATED in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotIn(List<String> values) {
            addCriterion("UPDATED not in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedBetween(String value1, String value2) {
            addCriterion("UPDATED between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotBetween(String value1, String value2) {
            addCriterion("UPDATED not between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andNivelIsNull() {
            addCriterion("NIVEL is null");
            return (Criteria) this;
        }

        public Criteria andNivelIsNotNull() {
            addCriterion("NIVEL is not null");
            return (Criteria) this;
        }

        public Criteria andNivelEqualTo(Long value) {
            addCriterion("NIVEL =", value, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelNotEqualTo(Long value) {
            addCriterion("NIVEL <>", value, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelGreaterThan(Long value) {
            addCriterion("NIVEL >", value, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelGreaterThanOrEqualTo(Long value) {
            addCriterion("NIVEL >=", value, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelLessThan(Long value) {
            addCriterion("NIVEL <", value, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelLessThanOrEqualTo(Long value) {
            addCriterion("NIVEL <=", value, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelIn(List<Long> values) {
            addCriterion("NIVEL in", values, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelNotIn(List<Long> values) {
            addCriterion("NIVEL not in", values, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelBetween(Long value1, Long value2) {
            addCriterion("NIVEL between", value1, value2, "nivel");
            return (Criteria) this;
        }

        public Criteria andNivelNotBetween(Long value1, Long value2) {
            addCriterion("NIVEL not between", value1, value2, "nivel");
            return (Criteria) this;
        }

        public Criteria andOrdenIsNull() {
            addCriterion("ORDEN is null");
            return (Criteria) this;
        }

        public Criteria andOrdenIsNotNull() {
            addCriterion("ORDEN is not null");
            return (Criteria) this;
        }

        public Criteria andOrdenEqualTo(Long value) {
            addCriterion("ORDEN =", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenNotEqualTo(Long value) {
            addCriterion("ORDEN <>", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenGreaterThan(Long value) {
            addCriterion("ORDEN >", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenGreaterThanOrEqualTo(Long value) {
            addCriterion("ORDEN >=", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenLessThan(Long value) {
            addCriterion("ORDEN <", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenLessThanOrEqualTo(Long value) {
            addCriterion("ORDEN <=", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenIn(List<Long> values) {
            addCriterion("ORDEN in", values, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenNotIn(List<Long> values) {
            addCriterion("ORDEN not in", values, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenBetween(Long value1, Long value2) {
            addCriterion("ORDEN between", value1, value2, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenNotBetween(Long value1, Long value2) {
            addCriterion("ORDEN not between", value1, value2, "orden");
            return (Criteria) this;
        }

        public Criteria andActivoIsNull() {
            addCriterion("ACTIVO is null");
            return (Criteria) this;
        }

        public Criteria andActivoIsNotNull() {
            addCriterion("ACTIVO is not null");
            return (Criteria) this;
        }

        public Criteria andActivoEqualTo(Short value) {
            addCriterion("ACTIVO =", value, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoNotEqualTo(Short value) {
            addCriterion("ACTIVO <>", value, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoGreaterThan(Short value) {
            addCriterion("ACTIVO >", value, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoGreaterThanOrEqualTo(Short value) {
            addCriterion("ACTIVO >=", value, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoLessThan(Short value) {
            addCriterion("ACTIVO <", value, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoLessThanOrEqualTo(Short value) {
            addCriterion("ACTIVO <=", value, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoIn(List<Short> values) {
            addCriterion("ACTIVO in", values, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoNotIn(List<Short> values) {
            addCriterion("ACTIVO not in", values, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoBetween(Short value1, Short value2) {
            addCriterion("ACTIVO between", value1, value2, "activo");
            return (Criteria) this;
        }

        public Criteria andActivoNotBetween(Short value1, Short value2) {
            addCriterion("ACTIVO not between", value1, value2, "activo");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioCreacionIsNull() {
            addCriterion("AUDIT_USUARIO_CREACION is null");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioCreacionIsNotNull() {
            addCriterion("AUDIT_USUARIO_CREACION is not null");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioCreacionEqualTo(String value) {
            addCriterion("AUDIT_USUARIO_CREACION =", value, "auditUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioCreacionNotEqualTo(String value) {
            addCriterion("AUDIT_USUARIO_CREACION <>", value, "auditUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioCreacionGreaterThan(String value) {
            addCriterion("AUDIT_USUARIO_CREACION >", value, "auditUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioCreacionGreaterThanOrEqualTo(String value) {
            addCriterion("AUDIT_USUARIO_CREACION >=", value, "auditUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioCreacionLessThan(String value) {
            addCriterion("AUDIT_USUARIO_CREACION <", value, "auditUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioCreacionLessThanOrEqualTo(String value) {
            addCriterion("AUDIT_USUARIO_CREACION <=", value, "auditUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioCreacionLike(String value) {
            addCriterion("AUDIT_USUARIO_CREACION like", value, "auditUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioCreacionNotLike(String value) {
            addCriterion("AUDIT_USUARIO_CREACION not like", value, "auditUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioCreacionIn(List<String> values) {
            addCriterion("AUDIT_USUARIO_CREACION in", values, "auditUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioCreacionNotIn(List<String> values) {
            addCriterion("AUDIT_USUARIO_CREACION not in", values, "auditUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioCreacionBetween(String value1, String value2) {
            addCriterion("AUDIT_USUARIO_CREACION between", value1, value2, "auditUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioCreacionNotBetween(String value1, String value2) {
            addCriterion("AUDIT_USUARIO_CREACION not between", value1, value2, "auditUsuarioCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioModificaIsNull() {
            addCriterion("AUDIT_USUARIO_MODIFICA is null");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioModificaIsNotNull() {
            addCriterion("AUDIT_USUARIO_MODIFICA is not null");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioModificaEqualTo(String value) {
            addCriterion("AUDIT_USUARIO_MODIFICA =", value, "auditUsuarioModifica");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioModificaNotEqualTo(String value) {
            addCriterion("AUDIT_USUARIO_MODIFICA <>", value, "auditUsuarioModifica");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioModificaGreaterThan(String value) {
            addCriterion("AUDIT_USUARIO_MODIFICA >", value, "auditUsuarioModifica");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioModificaGreaterThanOrEqualTo(String value) {
            addCriterion("AUDIT_USUARIO_MODIFICA >=", value, "auditUsuarioModifica");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioModificaLessThan(String value) {
            addCriterion("AUDIT_USUARIO_MODIFICA <", value, "auditUsuarioModifica");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioModificaLessThanOrEqualTo(String value) {
            addCriterion("AUDIT_USUARIO_MODIFICA <=", value, "auditUsuarioModifica");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioModificaLike(String value) {
            addCriterion("AUDIT_USUARIO_MODIFICA like", value, "auditUsuarioModifica");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioModificaNotLike(String value) {
            addCriterion("AUDIT_USUARIO_MODIFICA not like", value, "auditUsuarioModifica");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioModificaIn(List<String> values) {
            addCriterion("AUDIT_USUARIO_MODIFICA in", values, "auditUsuarioModifica");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioModificaNotIn(List<String> values) {
            addCriterion("AUDIT_USUARIO_MODIFICA not in", values, "auditUsuarioModifica");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioModificaBetween(String value1, String value2) {
            addCriterion("AUDIT_USUARIO_MODIFICA between", value1, value2, "auditUsuarioModifica");
            return (Criteria) this;
        }

        public Criteria andAuditUsuarioModificaNotBetween(String value1, String value2) {
            addCriterion("AUDIT_USUARIO_MODIFICA not between", value1, value2, "auditUsuarioModifica");
            return (Criteria) this;
        }

        public Criteria andAuditFechaCreacionIsNull() {
            addCriterion("AUDIT_FECHA_CREACION is null");
            return (Criteria) this;
        }

        public Criteria andAuditFechaCreacionIsNotNull() {
            addCriterion("AUDIT_FECHA_CREACION is not null");
            return (Criteria) this;
        }

        public Criteria andAuditFechaCreacionEqualTo(Date value) {
            addCriterion("AUDIT_FECHA_CREACION =", value, "auditFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditFechaCreacionNotEqualTo(Date value) {
            addCriterion("AUDIT_FECHA_CREACION <>", value, "auditFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditFechaCreacionGreaterThan(Date value) {
            addCriterion("AUDIT_FECHA_CREACION >", value, "auditFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditFechaCreacionGreaterThanOrEqualTo(Date value) {
            addCriterion("AUDIT_FECHA_CREACION >=", value, "auditFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditFechaCreacionLessThan(Date value) {
            addCriterion("AUDIT_FECHA_CREACION <", value, "auditFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditFechaCreacionLessThanOrEqualTo(Date value) {
            addCriterion("AUDIT_FECHA_CREACION <=", value, "auditFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditFechaCreacionIn(List<Date> values) {
            addCriterion("AUDIT_FECHA_CREACION in", values, "auditFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditFechaCreacionNotIn(List<Date> values) {
            addCriterion("AUDIT_FECHA_CREACION not in", values, "auditFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditFechaCreacionBetween(Date value1, Date value2) {
            addCriterion("AUDIT_FECHA_CREACION between", value1, value2, "auditFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditFechaCreacionNotBetween(Date value1, Date value2) {
            addCriterion("AUDIT_FECHA_CREACION not between", value1, value2, "auditFechaCreacion");
            return (Criteria) this;
        }

        public Criteria andAuditFechaModificaIsNull() {
            addCriterion("AUDIT_FECHA_MODIFICA is null");
            return (Criteria) this;
        }

        public Criteria andAuditFechaModificaIsNotNull() {
            addCriterion("AUDIT_FECHA_MODIFICA is not null");
            return (Criteria) this;
        }

        public Criteria andAuditFechaModificaEqualTo(Date value) {
            addCriterion("AUDIT_FECHA_MODIFICA =", value, "auditFechaModifica");
            return (Criteria) this;
        }

        public Criteria andAuditFechaModificaNotEqualTo(Date value) {
            addCriterion("AUDIT_FECHA_MODIFICA <>", value, "auditFechaModifica");
            return (Criteria) this;
        }

        public Criteria andAuditFechaModificaGreaterThan(Date value) {
            addCriterion("AUDIT_FECHA_MODIFICA >", value, "auditFechaModifica");
            return (Criteria) this;
        }

        public Criteria andAuditFechaModificaGreaterThanOrEqualTo(Date value) {
            addCriterion("AUDIT_FECHA_MODIFICA >=", value, "auditFechaModifica");
            return (Criteria) this;
        }

        public Criteria andAuditFechaModificaLessThan(Date value) {
            addCriterion("AUDIT_FECHA_MODIFICA <", value, "auditFechaModifica");
            return (Criteria) this;
        }

        public Criteria andAuditFechaModificaLessThanOrEqualTo(Date value) {
            addCriterion("AUDIT_FECHA_MODIFICA <=", value, "auditFechaModifica");
            return (Criteria) this;
        }

        public Criteria andAuditFechaModificaIn(List<Date> values) {
            addCriterion("AUDIT_FECHA_MODIFICA in", values, "auditFechaModifica");
            return (Criteria) this;
        }

        public Criteria andAuditFechaModificaNotIn(List<Date> values) {
            addCriterion("AUDIT_FECHA_MODIFICA not in", values, "auditFechaModifica");
            return (Criteria) this;
        }

        public Criteria andAuditFechaModificaBetween(Date value1, Date value2) {
            addCriterion("AUDIT_FECHA_MODIFICA between", value1, value2, "auditFechaModifica");
            return (Criteria) this;
        }

        public Criteria andAuditFechaModificaNotBetween(Date value1, Date value2) {
            addCriterion("AUDIT_FECHA_MODIFICA not between", value1, value2, "auditFechaModifica");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 10 12:11:13 PET 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}