package pe.gob.minjus.sisarb.auto.domain;

import java.util.Date;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.MENU_ID
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private Long menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.NOMBRE
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private String nombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.TIPO
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private String tipo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.MENU_PADRE
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private Long menuPadre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.URL
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.COMMAND
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private String command;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.ICON
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.AJAX
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private Short ajax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.UPDATED
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private String updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.NIVEL
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private Long nivel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.ORDEN
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private Long orden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.ACTIVO
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private Short activo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.AUDIT_USUARIO_CREACION
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private String auditUsuarioCreacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.AUDIT_USUARIO_MODIFICA
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private String auditUsuarioModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.AUDIT_FECHA_CREACION
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private Date auditFechaCreacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINJUSDH.GEN_MENU.AUDIT_FECHA_MODIFICA
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    private Date auditFechaModifica;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.MENU_ID
     *
     * @return the value of MINJUSDH.GEN_MENU.MENU_ID
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.MENU_ID
     *
     * @param menuId the value for MINJUSDH.GEN_MENU.MENU_ID
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.NOMBRE
     *
     * @return the value of MINJUSDH.GEN_MENU.NOMBRE
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.NOMBRE
     *
     * @param nombre the value for MINJUSDH.GEN_MENU.NOMBRE
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.TIPO
     *
     * @return the value of MINJUSDH.GEN_MENU.TIPO
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.TIPO
     *
     * @param tipo the value for MINJUSDH.GEN_MENU.TIPO
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.MENU_PADRE
     *
     * @return the value of MINJUSDH.GEN_MENU.MENU_PADRE
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public Long getMenuPadre() {
        return menuPadre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.MENU_PADRE
     *
     * @param menuPadre the value for MINJUSDH.GEN_MENU.MENU_PADRE
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setMenuPadre(Long menuPadre) {
        this.menuPadre = menuPadre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.URL
     *
     * @return the value of MINJUSDH.GEN_MENU.URL
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.URL
     *
     * @param url the value for MINJUSDH.GEN_MENU.URL
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.COMMAND
     *
     * @return the value of MINJUSDH.GEN_MENU.COMMAND
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public String getCommand() {
        return command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.COMMAND
     *
     * @param command the value for MINJUSDH.GEN_MENU.COMMAND
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setCommand(String command) {
        this.command = command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.ICON
     *
     * @return the value of MINJUSDH.GEN_MENU.ICON
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.ICON
     *
     * @param icon the value for MINJUSDH.GEN_MENU.ICON
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.AJAX
     *
     * @return the value of MINJUSDH.GEN_MENU.AJAX
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public Short getAjax() {
        return ajax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.AJAX
     *
     * @param ajax the value for MINJUSDH.GEN_MENU.AJAX
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setAjax(Short ajax) {
        this.ajax = ajax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.UPDATED
     *
     * @return the value of MINJUSDH.GEN_MENU.UPDATED
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public String getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.UPDATED
     *
     * @param updated the value for MINJUSDH.GEN_MENU.UPDATED
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setUpdated(String updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.NIVEL
     *
     * @return the value of MINJUSDH.GEN_MENU.NIVEL
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public Long getNivel() {
        return nivel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.NIVEL
     *
     * @param nivel the value for MINJUSDH.GEN_MENU.NIVEL
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setNivel(Long nivel) {
        this.nivel = nivel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.ORDEN
     *
     * @return the value of MINJUSDH.GEN_MENU.ORDEN
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public Long getOrden() {
        return orden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.ORDEN
     *
     * @param orden the value for MINJUSDH.GEN_MENU.ORDEN
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setOrden(Long orden) {
        this.orden = orden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.ACTIVO
     *
     * @return the value of MINJUSDH.GEN_MENU.ACTIVO
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public Short getActivo() {
        return activo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.ACTIVO
     *
     * @param activo the value for MINJUSDH.GEN_MENU.ACTIVO
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setActivo(Short activo) {
        this.activo = activo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.AUDIT_USUARIO_CREACION
     *
     * @return the value of MINJUSDH.GEN_MENU.AUDIT_USUARIO_CREACION
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public String getAuditUsuarioCreacion() {
        return auditUsuarioCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.AUDIT_USUARIO_CREACION
     *
     * @param auditUsuarioCreacion the value for MINJUSDH.GEN_MENU.AUDIT_USUARIO_CREACION
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setAuditUsuarioCreacion(String auditUsuarioCreacion) {
        this.auditUsuarioCreacion = auditUsuarioCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.AUDIT_USUARIO_MODIFICA
     *
     * @return the value of MINJUSDH.GEN_MENU.AUDIT_USUARIO_MODIFICA
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public String getAuditUsuarioModifica() {
        return auditUsuarioModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.AUDIT_USUARIO_MODIFICA
     *
     * @param auditUsuarioModifica the value for MINJUSDH.GEN_MENU.AUDIT_USUARIO_MODIFICA
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setAuditUsuarioModifica(String auditUsuarioModifica) {
        this.auditUsuarioModifica = auditUsuarioModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.AUDIT_FECHA_CREACION
     *
     * @return the value of MINJUSDH.GEN_MENU.AUDIT_FECHA_CREACION
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public Date getAuditFechaCreacion() {
        return auditFechaCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.AUDIT_FECHA_CREACION
     *
     * @param auditFechaCreacion the value for MINJUSDH.GEN_MENU.AUDIT_FECHA_CREACION
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setAuditFechaCreacion(Date auditFechaCreacion) {
        this.auditFechaCreacion = auditFechaCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINJUSDH.GEN_MENU.AUDIT_FECHA_MODIFICA
     *
     * @return the value of MINJUSDH.GEN_MENU.AUDIT_FECHA_MODIFICA
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public Date getAuditFechaModifica() {
        return auditFechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINJUSDH.GEN_MENU.AUDIT_FECHA_MODIFICA
     *
     * @param auditFechaModifica the value for MINJUSDH.GEN_MENU.AUDIT_FECHA_MODIFICA
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    public void setAuditFechaModifica(Date auditFechaModifica) {
        this.auditFechaModifica = auditFechaModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MINJUSDH.GEN_MENU
     *
     * @mbg.generated Tue Jan 10 12:11:13 PET 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuId=").append(menuId);
        sb.append(", nombre=").append(nombre);
        sb.append(", tipo=").append(tipo);
        sb.append(", menuPadre=").append(menuPadre);
        sb.append(", url=").append(url);
        sb.append(", command=").append(command);
        sb.append(", icon=").append(icon);
        sb.append(", ajax=").append(ajax);
        sb.append(", updated=").append(updated);
        sb.append(", nivel=").append(nivel);
        sb.append(", orden=").append(orden);
        sb.append(", activo=").append(activo);
        sb.append(", auditUsuarioCreacion=").append(auditUsuarioCreacion);
        sb.append(", auditUsuarioModifica=").append(auditUsuarioModifica);
        sb.append(", auditFechaCreacion=").append(auditFechaCreacion);
        sb.append(", auditFechaModifica=").append(auditFechaModifica);
        sb.append("]");
        return sb.toString();
    }
}